credentials:
  usernames:
    "gil@zed66.com":
      email: gil@zed66.com
      name: Gil Admin
      password: "$2b$12$IvIIEFFytxyg.IpbD6KoDuLkNNhuJwGmMIc4PIVabTxHmQ8kGV8X2"
      role: admin
    "gil@greenseo.co.il":
      email: gil@greenseo.co.il
      name: Gil User
      password: "$2b$12$3xbpHiaFweRaA0JEy.reQeWCLjvtrDubUWPuqyzQdYoLCAqPhAEe."
      role: user

cookie:
  expiry_days: 7
  key: musicnet_secret_key_2026
  name: musicnet_auth

pre-authorized:
  emails: []
